"""empty message

Revision ID: 9d25b0f470e4
Revises: 467a8a437549
Create Date: 2018-08-27 11:10:15.043836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d25b0f470e4'
down_revision = '467a8a437549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rate', ['id'])
    op.create_unique_constraint(None, 'request', ['id'])
    op.create_unique_constraint(None, 'ride', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'ride', type_='unique')
    op.drop_constraint(None, 'request', type_='unique')
    op.drop_constraint(None, 'rate', type_='unique')
    # ### end Alembic commands ###
